spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/daily_health_reminder_dev
      auto-index-creation: true

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    com.dailyhealthreminder: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/daily-health-reminder-dev.log

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true